### ISSUE TITLE
DisconnectedError(websocket was closed) when run multiple transactions at once.

### ISSUE THREAD

**Issue by StarNeit** [ripple/ripple-lib#1055]
When I run 1000 transactions using ripple-lib at once using Promise.all, there is `DisconnectedError(websocket was closed)`.

Here is my code snippet.
`

    const api = new RippleAPI({
        server: 'wss://s1.ripple.com' // Public rippled server hosted by Ripple, Inc.
    });
    if (!api.isConnected()) {
        console.log(`\n Connecting Ripple Server .....`);
        await api.connect();
    }

    const users = await WalletAddress.find({}); // users is array of 1000 members

    await Promise.all(users.map(async (user, index) => {
        console.log(index, user.phone, user.balance);
        if (user.balance > 0) {
            const xrpHashes = await sendXRP(api, user.fromXRPAddress, user.toXRPAddress, user.balance);
            console.log(index, user.phone, user.balance);
            console.log('xrpHashes:', xrpHashes);
        }
    }));` 
In my project, I have to run every user's transactions together every 2 minutes.

Here are my questions.
1) How many transactions `RippleAPI connection` can process at once?
2) Is it okay to create multiple connections and connect to rippled server instead of one connection? Will that resolve DisconnectedError?

Please suggest any good solution to avoid this Disconnection error.
Thank you.

**Comment by StarNeit** [comment]
![image](https://user-images.githubusercontent.com/16525001/67203682-08723c80-f40c-11e9-9c77-caf27ad34bee.png)

**Comment by StarNeit** [comment]
Hello @intelliot 
Would you please give me one of your advices to avoid this issue?

**Comment by intelliot** [comment]
Public rippled servers like s1.ripple.com have rate limits in place. I recommend running your own instance of rippled and connecting to it with an admin connection. This will allow you to submit more transactions more quickly.

**Comment by StarNeit** [comment]
Ok we just deployed custom rippled server but couldn’t find a way how to connect to the server from your documentation.
Should we add public domain for our rippled server? which port should we connect?

**Comment by intelliot** [comment]
A public domain is not necessary, and in fact your server does not necessarily need to be publicly accessible. You can choose the port. The [example rippled.cfg configuration](https://github.com/ripple/rippled/blob/develop/cfg/rippled-example.cfg#L1147) offers an admin connection on port 6006 when connecting from the same machine (127.0.0.1).

**Comment by kgh2927845** [comment]
@intelliot Thanks for the advise. We successfully connected to our rippled server but still have an issue submitting transactions.
We've got BAD_AUTH issue, still couldn't resolve this.

{
resultCode: 'tefBAD_AUTH',
  resultMessage: 'Transaction\'s public key is not authorized.',
  engine_result: 'tefBAD_AUTH',
  engine_result_code: -196,
...}

Could you please advise what additional configuration we need to add?

**Comment by StarNeit** [comment]
@intelliot , would you please help with the above issue? thank you a lot.

**Comment by intelliot** [comment]
It sounds like your secret or private key is incorrect or does not match the account that you're trying to send from.

**Comment by kgh2927845** [comment]
@intelliot We submitted transactions signed offline.
Should we do something on our rippled server?

**Comment by ximinez** [comment]
The only possible server configuration that I can think of is the choice of which network the server is connecting to. For example, if it's connected to the Altnet (https://xrpl.org/connect-your-rippled-to-the-xrp-test-net.html), and you submit a transaction signed for the Main Net, it will probably never succeed, and vice versa. (I only say "probably" because, even though it is *strongly* not recommended, accounts can be created on both networks using the same keys, but they won't have the same settings, unless they are manually configured that way on both networks.)

If that's not the issue, it's much more likely that the transaction is not being properly signed.

**Comment by kgh2927845** [comment]
@ximinez Thank you for the advise.
