### ISSUE TITLE
Serialized transaction does not match original txJSON due to wrong serialization / deserialization of paths

### ISSUE THREAD

**Issue by tadejgolobic** [ripple/ripple-lib#1347]
We have an issue with signing transaction that has paths field specified. It looks like that paths object needs to have all three fields specified (account, issuer and currency). In case one of them is not defined / not provided, then ripple-lib will throw following error:
`Serialized transaction does not match original txJSON. See error.data`.

Lets look at this example:
   ```
const pathfind = {
        source: {
            address: 'rNf1i8YPXbV3Nh4FDsJiyENqMmGN8PnaLR',
            maxAmount: {
                currency: 'drops',
                amount: '100'
            }
        },
        destination: {
          address: 'rKT4JX4cCof6LcDYRz8o3rGRu7qxzZ2Zwj',
          amount: {
            value: '1',
            currency: 'USD',
            counterparty: 'rVnYNK9yuxBz4uP8zC8LEFokM2nqH3poc'
          }
        }
    }

    xrp.getPaths(pathfind).then(data => {
        pathfind.paths = data[0].paths;
        xrp.preparePayment('rNf1i8YPXbV3Nh4FDsJiyENqMmGN8PnaLR', pathfind).then(ret => {
            const signed = xrp.sign(ret.txJSON, wallet.secret);
        }).catch(err => {
            console.log('ERR: ', err);
        })
    }).catch(err => {
        console.log('ERR: ', err);
    })
```

With this example we get error as described above. We also found out, that this happens because of `ripple-binary-codec`.

If we check following code:
```

const txJSON = {
    Fee: "45",
    Amount: "1000000",
    Account: "rMqzrqJgSVzfKEJNyTxJnkpybMBjTTfuef",
    Destination: "rVnYNK9yuxBz4uP8zC8LEFokM2nqH3poc",
    TransactionType: "Payment",
    Paths: [
        [
            { account: 'rVnYNK9yuxBz4uP8zC8LEFokM2nqH3poc'}
        ]
    ]
}


const encoded = binaryCodec.encode(txJSON)
const decoded = binaryCodec.decode(encoded);

console.log('DECODED: ', decoded['Paths']);
```

this is the output:

```
"DECODED: " [
  [
    {
      account: 'rVnYNK9yuxBz4uP8zC8LEFokM2nqH3poc',
      issuer: undefined,
      currency: undefined
    }
  ]
]
```

So issue is that everytime, paths will be defined and one of the PathFind fields will not be defined, we cannot sign transaction. I would also like to point out, that in paths, we cannot pass undefined values from our side, to ripple-lib, because txJSON must be passed as string, and we cannot stringify undefined values.

I would also like to ask following question:
Is it absolutely necessary to do encode, and then immediately decode here: https://github.com/ripple/ripple-lib/blob/develop/src/transaction/sign.ts#L59 (decode is performed inside checkTxSerialization function)

**Comment by alexdupre** [comment]
This looks like a serious regression, that makes often impossible to use the result of the `getPaths` to prepare and sign a payment. It started happening in the 1.9.0 release (that updated the `ripple-binary-codec` dependency).

**Comment by intelliot** [comment]
If you use ripple-lib 1.8.2, does everything work fine?

**Comment by tadejgolobic** [comment]
@alexdupre @intelliot this was issue in `ripple-binary-codec`. Here is issue https://github.com/ripple/ripple-binary-codec/issues/117

I already opened PR and PR was also merged. Should be fixed in next release.

**Comment by nickvujasin** [comment]
Hey guys, was running into this issue with 1.9 and just found this thread. I'm assuming it isn't fixed in 1.9.1 because I just upgraded and it's still occurring. Do you have a time frame as to when this will be released?

**Comment by nickvujasin** [comment]
@intelliot Hi Elliot, I was hoping you could give us some insight as to when this will be released. I see that this issue has been open since January and the PR to fix this has been out there for 14 days. I agree with Alex that this is a critical piece of functionality, it is what the XRPL was designed to do, payments and right now 1.9 and 1.9.1 can't make them.  Thanks, Nick

**Comment by intelliot** [comment]
Thank you all for reporting this, especially @tadejgolobic for the code sample

**Comment by nickvujasin** [comment]
@intelliot Hey Elliot, thank you for getting this fix in and with an immediate release. I very much appreciate it. Nick

**Comment by Satosh-J** [comment]
Hi, intelliot.
I have _ValidationError: Serialized transaction does not match original txJSON. See error.data_

```
const transactionBlob = {
		"TransactionType": "NFTokenAcceptOffer",
		"Account": wallet.classicAddress,
		"SellOffer": tokenOfferIndex,
	}

const tx = await client.submitAndWait(transactionBlob, { wallet })
```
this is NFTokenOffer accept tx.
This is the error data
```
{
    "name": "ValidationError",
    "data": {
        "decoded": {
            "TransactionType": "NFTokenAcceptOffer",
            "Flags": 0,
            "Sequence": 1824368,
            "LastLedgerSequence": 2200579,
            "Fee": "12",
            "Account": "rNZ8EFNxCTf2sZTVExQgayqPRsGZK9AgQ8"
        },
        "tx": {
            "TransactionType": "NFTokenAcceptOffer",
            "Account": "rNZ8EFNxCTf2sZTVExQgayqPRsGZK9AgQ8",
            "SellOffer": "A6BC70E852CBED46BD1DF60909AC1D4DD328C588BE3F7CF774229088BCFBD665",
            "Flags": 0,
            "Sequence": 1824368,
            "Fee": "12",
            "LastLedgerSequence": 2200579
        }
    }
}
```

Please let me know the reason. Thanks.

**Comment by JST5000** [comment]
@Satosh-J I think the issue is that you have a field "SellOffer", when it should be "NFTokenSellOffer" - https://xrpl.org/nftokenacceptoffer.html#nftokenacceptoffer

(This was a recent change to the NFT naming conventions to standardize it)

**Comment by intelliot** [comment]
@Satosh-J If the problem persists, please create a [new issue here](https://github.com/XRPLF/xrpl.js/issues/new/choose). (This existing issue is an old one which was resolved/closed)
